// Kaduse lane change artifacts. Kaduse feeds reach D1 only through forward migrations (migration governance), so a
// Kaduse lifecycle operation with --apply:
//   1. edits the canonical catalog record (packages/source-catalog/data/*.json -- the only editable source truth),
//   2. regenerates config/feeds.json with scripts/sync-feeds.mjs (never hand-edited),
//   3. emits the NEXT forward migration, derived deterministically from the feeds.json diff.
// The migration is never applied here. Remote apply (`wrangler d1 migrations apply global-content-os --remote`) stays the
// explicit review/authorization gate. The pipeline always runs in a disposable sandbox under the OS temp dir; repo files
// are written only through store.writeCanonicalFiles after authorization and apply === true.
import { readFileSync, writeFileSync, mkdtempSync, cpSync, rmSync, readdirSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { execFileSync } from 'node:child_process';
import { authorizeLifecycle, writeCanonicalFiles } from './store.mjs';

export const KADUSE_FILES = {
  subscriptions: 'packages/source-catalog/data/kaduse-subscriptions.json',
  news: 'packages/source-catalog/data/news-registry.json',
  research: 'packages/source-catalog/data/research-sources.json',
};
const SYNC_INPUTS = ['scripts/sync-feeds.mjs', 'packages/source-catalog/data', 'adapters/hekimler-radar/sources/official_sources.yaml', 'config/feeds.json'];
// Columns the catalog owns; runtime columns (last_fetched_at, health, counters) are never touched by a lifecycle migration.
const MANAGED = ['label', 'route', 'channel_id', 'transport', 'endpoint_url', 'poll_minutes', 'enabled', 'external_ref', 'rules_json'];

const sq = (s) => String(s).replace(/'/g, "''");
const row = (f) => ({
  id: f.id,
  label: f.label ?? f.id,
  route: f.route,
  channel_id: f.channelId ?? 'kaduse-medikal',
  transport: f.transport ?? 'WEB_ONLY',
  endpoint_url: f.endpointUrl ?? null,
  poll_minutes: Number(f.pollMinutes) || 360,
  enabled: f.enabled ? 1 : 0,
  external_ref: f.externalRef ?? null,
  rules_json: JSON.stringify(f.rules ?? {}),
});
const lit = (v) => (v === null ? 'NULL' : typeof v === 'number' ? String(v) : `'${sq(v)}'`);

/** Rows that must change in D1: new/changed feeds are upserted; feeds that disappeared are disabled, never deleted. */
export function diffFeeds(before, after) {
  const b = new Map(before.map((f) => [f.id, row(f)]));
  const a = new Map(after.map((f) => [f.id, row(f)]));
  const upserts = [];
  const disables = [];
  for (const [id, r] of a) if (JSON.stringify(b.get(id)) !== JSON.stringify(r)) upserts.push(r);
  for (const [id, r] of b) if (!a.has(id) && r.enabled === 1) disables.push(id);
  upserts.sort((x, y) => x.id.localeCompare(y.id));
  disables.sort();
  return { upserts, disables };
}

export function forwardMigrationSql({ upserts, disables }, { op, sourceId, requestId }) {
  const lines = [
    `-- Generated by scripts/source-lifecycle.mjs (${op} ${sourceId}, request ${requestId}) from the config/feeds.json diff.`,
    '-- Forward-only; catalog-owned columns only. Remote apply requires explicit authorization.',
    '',
  ];
  for (const r of upserts) {
    lines.push(`INSERT INTO source_feeds (id, ${MANAGED.join(', ')})`);
    lines.push(`VALUES (${[r.id, ...MANAGED.map((k) => r[k])].map(lit).join(', ')})`);
    lines.push(`ON CONFLICT(id) DO UPDATE SET ${MANAGED.map((k) => `${k} = excluded.${k}`).join(', ')};`);
    lines.push('');
  }
  for (const id of disables) lines.push(`UPDATE source_feeds SET enabled = 0 WHERE id = '${sq(id)}';`, '');
  return lines.join('\n');
}

export function nextMigrationFile(root, slug) {
  let names = [];
  try {
    names = readdirSync(join(root, 'migrations'));
  } catch {
    names = [];
  }
  const nums = names.map((n) => /^(\d{4})_/.exec(n)?.[1]).filter(Boolean).map(Number);
  const next = String(Math.max(0, ...nums) + 1).padStart(4, '0');
  return `migrations/${next}_source_lifecycle_${slug.replace(/[^a-z0-9]+/gi, '_').toLowerCase().replace(/^_+|_+$/g, '').slice(0, 48)}.sql`;
}

const parse = (raw) => ({ data: JSON.parse(raw), eol: raw.includes('\r\n') ? '\r\n' : '\n', trailing: raw.endsWith('\n') });
const serialize = ({ data, eol, trailing }) => (JSON.stringify(data, null, 2) + (trailing ? '\n' : '')).split('\n').join(eol);

/** Catalog mutations per operation. Each returns a compact patch, { noop } or { error }. */
export const MUTATIONS = {
  retire(files, m) {
    if (m.lane === 'kaduse-news') {
      const s = files.subscriptions.data.subscriptions.find((x) => x.targetId === m.source_id);
      if (!s) return { error: 'SUBSCRIPTION_NOT_FOUND' };
      if (s.enabled === false) return { noop: true };
      s.enabled = false;
      return { files: ['subscriptions'], field: `subscriptions[targetId=${m.source_id}].enabled`, before: true, after: false };
    }
    const r = files.research.data.find((x) => x.sourceId === m.source_id);
    if (!r) return { error: 'RESEARCH_RECORD_NOT_FOUND' };
    if (r.verificationStatus === 'EXCLUDE') return { noop: true };
    const before = r.verificationStatus ?? null;
    r.retiredFromStatus = before;
    r.verificationStatus = 'EXCLUDE';
    return { files: ['research'], field: `[sourceId=${m.source_id}].verificationStatus`, before, after: 'EXCLUDE' };
  },
  reactivate(files, m) {
    if (m.lane === 'kaduse-news') {
      const s = files.subscriptions.data.subscriptions.find((x) => x.targetId === m.source_id);
      if (!s) return { error: 'SUBSCRIPTION_NOT_FOUND' };
      if (s.enabled === true) return { noop: true };
      s.enabled = true;
      return { files: ['subscriptions'], field: `subscriptions[targetId=${m.source_id}].enabled`, before: false, after: true };
    }
    const r = files.research.data.find((x) => x.sourceId === m.source_id);
    if (!r) return { error: 'RESEARCH_RECORD_NOT_FOUND' };
    if (r.verificationStatus !== 'EXCLUDE') return { noop: true };
    const after = r.retiredFromStatus || 'CONDITIONAL_VERIFIED';
    delete r.retiredFromStatus;
    r.verificationStatus = after;
    return { files: ['research'], field: `[sourceId=${m.source_id}].verificationStatus`, before: 'EXCLUDE', after };
  },
  add(files, v, { name, at }) {
    const url = v.endpoint.page_url || v.endpoint.url;
    const hostname = new URL(url).hostname;
    const slug = v.sourceId.replace(/[^a-z0-9]+/gi, '-').replace(/^-+|-+$/g, '').toLowerCase();
    const label = name || slug;
    const note = `Added by source-lifecycle ${at}: gates passed (identity, access, parser, routing, dedupe, cadence ${v.cadence.poll_minutes}min, canary). Endpoint ${v.endpoint.url}.`;
    if (v.routing.lane === 'kaduse-news') {
      const reg = files.news.data;
      const pubId = hostname.replace(/^www\./, '').split('.').slice(-2, -1)[0] || slug;
      if ((reg.sources || []).some((s) => s.id === slug) || reg.targets.some((t) => t.id === `${slug}-whole`)) return { error: 'ID_TAKEN' };
      reg.publishers ||= [];
      reg.sources ||= [];
      if (!reg.publishers.some((p) => p.id === pubId)) reg.publishers.push({ id: pubId, canonicalName: label, officialUrl: `https://${hostname}` });
      reg.sources.push({ id: slug, publisherId: pubId, canonicalName: label, officialUrl: url, status: 'ACTIVE', verificationStatus: 'PENDING_VERIFICATION', verificationNote: note });
      reg.targets.push({ id: `${slug}-whole`, sourceId: slug, label, officialUrl: url, scopeType: 'WHOLE_SOURCE', scopeDescription: note, transportStatus: 'WEB_ONLY', machineReadable: false });
      const subs = files.subscriptions.data;
      subs.subscriptions.push({ channelId: 'kaduse-medikal', sourceId: slug, targetId: `${slug}-whole`, enabled: true });
      if ('subscriptionCount' in subs) subs.subscriptionCount = subs.subscriptions.length;
      return { files: ['news', 'subscriptions'], insert: `${slug}-whole` };
    }
    if (files.research.data.some((r) => r.sourceId === slug)) return { error: 'ID_TAKEN' };
    files.research.data.push({ sourceId: slug, publisher: label, canonicalUrl: url, sourceRole: 'ACCESSIBLE_SCIENCE_MEDIA', discoveryFunction: 'DISCOVERY_SECONDARY', verificationStatus: 'PENDING_VERIFICATION', verifiedAt: null, notes: note });
    return { files: ['research'], insert: slug };
  },
};

/** Default sync: the real generator run inside the sandbox. */
export function realSync(dir) {
  execFileSync(process.execPath, [join(dir, 'scripts', 'sync-feeds.mjs')], { cwd: dir, stdio: 'pipe' });
  return JSON.parse(readFileSync(join(dir, 'config', 'feeds.json'), 'utf8')).feeds;
}

/**
 * Prepare (and with apply === true, write) one Kaduse lifecycle change.
 * Outcomes: CHANGE_DRY_RUN | CHANGE_PREPARED | NO_CHANGE | DENIED | BLOCKED_TECHNICAL.
 */
export function prepareKaduseChange({ root, op, target, mutateArgs = {}, apply = false, actor, authorize, requestId, sync = realSync }) {
  const box = mkdtempSync(join(tmpdir(), 'kaduse-change-'));
  try {
    for (const p of SYNC_INPUTS) {
      try {
        cpSync(join(root, p), join(box, p), { recursive: true });
      } catch {
        if (sync === realSync) return { outcome: 'BLOCKED_TECHNICAL', reason: `SYNC_INPUT_MISSING: ${p}` };
      }
    }
    const feedsText = readFileSync(join(box, 'config', 'feeds.json'), 'utf8');
    const before = JSON.parse(feedsText).feeds;
    const files = Object.fromEntries(Object.entries(KADUSE_FILES).map(([k, f]) => [k, parse(readFileSync(join(box, f), 'utf8'))]));
    const patch = MUTATIONS[op](files, target, mutateArgs);
    if (patch.error) return { outcome: 'BLOCKED_TECHNICAL', reason: patch.error };
    if (patch.noop) return { outcome: 'NO_CHANGE', reason: 'catalog record already in the requested state' };
    const changed = patch.files.map((k) => ({ file: KADUSE_FILES[k], text: serialize(files[k]) }));
    for (const w of changed) writeFileSync(join(box, w.file), w.text);
    const after = sync(box);
    const diff = diffFeeds(before, after);
    const publicPatch = { ...patch, files: changed.map((w) => w.file) };
    if (!diff.upserts.length && !diff.disables.length) {
      return { outcome: 'NO_CHANGE', patch: publicPatch, reason: 'no D1 feed row changes (a feed governed by PENDING_ACTIVATION_FEED_IDS / RETIRED_DUPLICATE_FEED_IDS in scripts/sync-feeds.mjs needs an explicit decision, not a lifecycle apply)' };
    }
    const sourceId = patch.insert || target.source_id;
    const migration = nextMigrationFile(root, `${op}_${sourceId}`);
    const sql = forwardMigrationSql(diff, { op, sourceId, requestId });
    const summary = { patch: publicPatch, migration, d1: { upserts: diff.upserts.map((r) => `${r.id} enabled=${r.enabled}`), disables: diff.disables } };
    if (apply !== true) return { outcome: 'CHANGE_DRY_RUN', ...summary, sql };
    const auth = authorizeLifecycle({ actor, authorize, op });
    if (!auth.ok) return { outcome: 'DENIED', ...summary, ...auth };
    writeCanonicalFiles(root, [...changed, { file: 'config/feeds.json', text: readFileSync(join(box, 'config', 'feeds.json'), 'utf8') }, { file: migration, text: sql }]);
    return {
      outcome: 'CHANGE_PREPARED',
      ...summary,
      review_gate: [
        `Review + commit: ${publicPatch.files.join(', ')}, config/feeds.json, ${migration}`,
        'Local validation: npx wrangler d1 migrations apply global-content-os --local; node scripts/registry-find.mjs <feed id>',
        'Remote (explicit authorization): npx wrangler d1 migrations apply global-content-os --remote',
      ],
    };
  } finally {
    rmSync(box, { recursive: true, force: true });
  }
}
