// Source lifecycle model. Persistent state is NOT a new enum: it is derived from the canonical fields the runtime
// already reads (Hekimler `status` + `runtime_activation`, Kaduse `enabled` / `activation` / subscription state).
// Transaction phases (REQUESTED .. ACTIVE) exist only in an operation's trace and are never written to a registry.

export const PHASES = ['REQUESTED', 'RESOLVING', 'VALIDATING', 'CANARY', 'READY', 'ACTIVE'];
export const EXCEPTIONAL = ['NEEDS_USER_DECISION', 'BLOCKED_ACCESS', 'BLOCKED_CAPACITY', 'BLOCKED_TECHNICAL', 'RETIRED'];
export const OUTCOMES = [...PHASES, ...EXCEPTIONAL, 'ALREADY_ACTIVE', 'ALREADY_RETIRED', 'NOT_FOUND', 'PLAN_ONLY'];

// Canonical Hekimler vocabulary (radar/hekimler_activation.py). Re-declared only to read it, never extended.
export const ACTIVATION = { READY: 'AUTOMATION_READY', MANUAL: 'MANUAL_INTAKE', BLOCKED: 'BLOCKED' };
export const HEKIMLER_STATUS = { ACTIVE: 'active', RETIRED: 'retired' };

export const LANES = {
  hekimler: {
    channelId: 'tip-ogrencileri-platformu',
    scheduler: 'hekimler-python-runner',
    runsPerDay: 1,
    store: 'adapters/hekimler-radar/content/source-registry-*.json',
    cadenceField: 'fetch_plan.expected_check_interval_minutes',
    apply: true,
  },
  'kaduse-news': {
    channelId: 'kaduse-medikal',
    scheduler: 'worker-cron',
    store: 'packages/source-catalog/data/{news-registry,kaduse-subscriptions}.json',
    cadenceField: 'config/feeds.json pollMinutes (generated by scripts/sync-feeds.mjs)',
    apply: false,
  },
  'kaduse-research': {
    channelId: 'kaduse-medikal',
    scheduler: 'worker-cron',
    store: 'packages/source-catalog/data/research-sources.json',
    cadenceField: 'config/feeds.json pollMinutes (generated by scripts/sync-feeds.mjs)',
    apply: false,
  },
};

/**
 * Derived lifecycle state of one canonical record projection (see catalog.mjs `project`).
 * INACTIVE = registered but not fetched (MANUAL_INTAKE, disabled, PENDING_EXPLICIT_DECISION);
 * READY = INACTIVE whose last lifecycle operation passed every gate except capacity.
 */
export function stateOf(p) {
  if (!p) return 'NOT_FOUND';
  if (p.retired) return 'RETIRED';
  if (p.active) return 'ACTIVE';
  return p.lastOutcome === 'READY' ? 'READY' : 'INACTIVE';
}
