/**
 * Honest coverage labels for the Hekimler source-health view. A source that is merely reachable must never look
 * like full coverage: limited / partial / runner-required sources are labelled explicitly.
 */
export type CoverageLabel =
  | 'PIPELINE_OK'
  | 'PIPELINE_OK_EMPTY'
  | 'PIPELINE_OK_LIMITED'
  | 'PARTIALLY_COVERED'
  | 'RUNNER_REQUIRED'
  | 'CONFIGURED_NOT_WIRED'
  | 'FAILED_INTERNAL'
  | 'NOT_RUN';

/** Burs lane sources (MANUAL_INTAKE until a verified list-page is wired). Always listed in Hub. */
export const HEKIMLER_BURS_SOURCE_IDS = [
  'burs_tr_fulbright',
  'burs_tr_humphrey',
  'burs_tr_meb_ylsy',
  'burs_tr_tubitak_2214',
  'burs_tr_tubitak_2219',
  'burs_us_aauw_international',
  'burs_de_daad',
  'burs_uk_chevening',
  'burs_eu_erasmus_mundus',
  'burs_jp_mext',
  'burs_uicc_technical',
  'burs_esot_grants',
  'burs_iadr_awards',
  'burs_eadv_scholarships',
  'burs_isn_fellowships',
  'burs_fip_foundation',
  'burs_esc_grants',
  'burs_esmo_fellowships',
  'burs_ean_fellowships',
  'burs_esso_grants',
  'burs_escmid_grants',
  'burs_eau_eusp',
  'burs_ers_fellowships',
  'burs_eacts_fontan',
  'burs_era_fellowships',
  'burs_asco_conquer',
  'burs_wsava_day',
  'burs_ectrims',
  'burs_ueg',
  'burs_esor',
  'burs_efsd_easd',
  'burs_eha_grants',
  'burs_ibro',
  'burs_fens',
  'burs_eular',
  'burs_iarc_who',
  'burs_sigma_nursing',
  'burs_uk_wellcome',
  'burs_tr_kyk',
  'burs_tr_tev',
  'burs_tr_tubitak_2209',
  'burs_tr_tubitak_2210',
  'burs_tr_tubitak_2211',
  'burs_hu_stipendium',
  'burs_tr_jean_monnet',
  'burs_fr_eiffel',
  'burs_kr_gks',
  'burs_ch_swiss_excellence',
  'burs_us_cri',
  'burs_us_fraxa',
  'burs_esicm_grants',
  'burs_espen_fellowships',
  'burs_febs_fellowships',
  'burs_embo',
  'burs_uk_mrc',
  'burs_iti_scholarships',
  'burs_esaic_grants',
  'burs_us_morris',
  'burs_us_pva',
  'burs_iubmb',
  'burs_eso_doctors',
  'burs_fip_ecpg',
  'burs_icm_congress',
  'burs_isa_wca_travel',
  'burs_imperial_gozukara',
] as const;

/** Prestige-education lane (MANUAL_INTAKE until a verified course catalogue is wired). */
export const HEKIMLER_EGITIM_SOURCE_IDS = [
  'egitim_ifm',
  'egitim_acam_chelation',
  'egitim_cleveland_cfm',
  'egitim_stanford_integrative',
  'egitim_charite_im_summer',
  'egitim_who_academy',
  'egitim_hms_ce',
  'egitim_mayo_scpd',
  'egitim_lshtm_short',
  'egitim_pasteur',
  'egitim_eso',
  'egitim_eau',
  'egitim_ean_learn',
  'egitim_esaic_academy',
  'egitim_ers',
  'egitim_eular',
  'egitim_eha',
  'egitim_fens',
  'egitim_febs_courses',
  'egitim_bif_travel',
  'egitim_eons_eso_nurses',
  'egitim_esso',
  'egitim_isglobal',
  'egitim_wcmq_cpd',
  'egitim_monash_pd',
  'egitim_wfot',
  'egitim_world_physio',
  'egitim_espen_training',
  'egitim_ifm_fmcp',
  'egitim_ifm_afmcp',
  'egitim_cleveland_observership',
  'egitim_uws_cnfm',
  'egitim_kresser_adapt',
  'egitim_fmca',
  'egitim_egfm',
  'egitim_nih_ippcr',
  'egitim_hms_hmx',
  'egitim_eso_medstudents',
  'egitim_esmo_students',
  'egitim_ucl_moorfields_oss',
  'egitim_erasmus_summer',
  'egitim_openwho',
] as const;

/** Same stream listed under two Hub headings — retired copy, keep the canonical heading. */
export const HEKIMLER_RETIRED_DUPLICATE_SOURCE_IDS = [
  'ema_news',
  'fierce_biotech',
  'medpage_today',
  'medical_xpress',
  'stat_news',
  'saglik_bakanligi_genel',
  // S57 (2026-09-26): aa.com.tr belongs to Kaduse (Haber) exclusively;
  // this Hekimler-side secondary registration is retired
  // (source-registry-phase1.json / -v1.1.json, status: retired).
  'anadolu_ajansi_medical_radar',
] as const;

/** Material, documented limitations (snapshot: adapters/hekimler-radar/content/archive/HEKIMLER-COVERAGE-MATRIX.md). */
export const COVERAGE_OVERRIDES: Record<string, { label: CoverageLabel; note: string }> = {
  abroad_uk_gmc: { label: 'PARTIALLY_COVERED', note: 'Yalnız gov.uk UKVI/DHSC beslemeleri; GMC kayıt/PLAB/haber kapsam dışı (bot engeli).' },
  abroad_us_ecfmg_intealth: { label: 'CONFIGURED_NOT_WIRED', note: 'Cloudflare/Radware bot koruması nedeniyle otomatik çekim bağlanmadı (configured_not_wired); yalnız USMLE/NRMP/AAMC komşu kapsam.' },
  abroad_de_make_it_in_germany: { label: 'CONFIGURED_NOT_WIRED', note: 'Kayıtlı ancak otomatik çekim bağlanmadı (configured_not_wired); yalnız tanınma (Anerkennung), vize/taşınma kapsam dışı.' },
  hsgm_public_health: { label: 'RUNNER_REQUIRED', note: 'GitHub çıkışından erişilemez; Türkiye çıkışlı runner gerekir.' },
  abroad_es_universidades_homologacion: { label: 'PIPELINE_OK_LIMITED', note: 'Tarih yalnız ay hassasiyetinde.' },
  pubmed_biomedical_evidence: { label: 'PIPELINE_OK_LIMITED', note: '90 gün, sınırlı yüksek değerli sorgular.' },
  burs_tr_fulbright: { label: 'RUNNER_REQUIRED', note: 'Burs şeridi: dönemsel resmi çağrı; otomatik list-page henüz açık değil.' },
  burs_tr_humphrey: { label: 'RUNNER_REQUIRED', note: 'Burs şeridi: yıllık çağrı; otomatik çekim kapalı.' },
  burs_tr_meb_ylsy: { label: 'RUNNER_REQUIRED', note: 'Burs şeridi: yıllık kılavuz; sağlık kontenjanı kontrolü elle.' },
  burs_tr_tubitak_2214: { label: 'RUNNER_REQUIRED', note: 'Burs şeridi: 2214-A çağrı sayfası; otomatik çekim kapalı.' },
  burs_tr_tubitak_2219: { label: 'RUNNER_REQUIRED', note: 'Burs şeridi: 2219 çağrı sayfası; otomatik çekim kapalı.' },
  burs_us_aauw_international: { label: 'RUNNER_REQUIRED', note: 'Burs şeridi: yıllık STEM fellowship; kadın + sağlık track.' },
  burs_de_daad: { label: 'RUNNER_REQUIRED', note: 'Burs şeridi: DAAD katalog; yalnız tıp/sağlık ilanları.' },
  burs_uk_chevening: { label: 'RUNNER_REQUIRED', note: 'Burs şeridi: yıllık UK master çağrısı.' },
  burs_eu_erasmus_mundus: { label: 'RUNNER_REQUIRED', note: 'Burs şeridi: resmi katalog; yalnız sağlık programları.' },
  burs_jp_mext: { label: 'RUNNER_REQUIRED', note: 'Burs şeridi: yıllık MEXT; TR Japonya Büyükelçiliği + YÖK duyurusu.' },
  burs_uicc_technical: { label: 'RUNNER_REQUIRED', note: "Burs şeridi: UICC teknik fellowship; öğrenci değil." },
  burs_esot_grants: { label: 'RUNNER_REQUIRED', note: "Burs şeridi: ESOT grant; TR Avrupa tanımında." },
  burs_iadr_awards: { label: 'RUNNER_REQUIRED', note: "Burs şeridi: IADR ödül/fellowship." },
  burs_eadv_scholarships: { label: 'RUNNER_REQUIRED', note: "Burs şeridi: EADV kongre/eğitim bursu." },
  burs_isn_fellowships: { label: 'RUNNER_REQUIRED', note: "Burs şeridi: ISN fellowship; UMIC." },
  burs_fip_foundation: { label: 'RUNNER_REQUIRED', note: "Burs şeridi: FIP Foundation eczacılık." },
  burs_esc_grants: { label: 'RUNNER_REQUIRED', note: "Burs şeridi: ESC grant/fellowship." },
  burs_esmo_fellowships: { label: 'RUNNER_REQUIRED', note: "Burs şeridi: ESMO fellowship; üyelik kontrol." },
  burs_ean_fellowships: { label: 'RUNNER_REQUIRED', note: "Burs şeridi: EAN fellowship." },
  burs_esso_grants: { label: 'RUNNER_REQUIRED', note: "Burs şeridi: ESSO educational grant." },
  burs_escmid_grants: { label: 'RUNNER_REQUIRED', note: "Burs şeridi: ESCMID grant/award." },
  burs_eau_eusp: { label: 'RUNNER_REQUIRED', note: "Burs şeridi: EUSP; 1 Ocak/Mayıs/Eylül." },
  burs_ers_fellowships: { label: 'RUNNER_REQUIRED', note: "Burs şeridi: ERS/RESPIRE." },
  burs_eacts_fontan: { label: 'RUNNER_REQUIRED', note: "Burs şeridi: Francis Fontan Fund." },
  burs_era_fellowships: { label: 'RUNNER_REQUIRED', note: "Burs şeridi: ERA fellowship; 2027 çağrı." },
  burs_asco_conquer: { label: 'RUNNER_REQUIRED', note: "Burs şeridi: Conquer Cancer/IDEA; TR UMIC." },
  burs_wsava_day: { label: 'RUNNER_REQUIRED', note: "Burs şeridi: WSAVA Michael J. Day." },
  burs_ectrims: { label: 'RUNNER_REQUIRED', note: "Burs şeridi: ECTRIMS fellowship." },
  burs_ueg: { label: 'RUNNER_REQUIRED', note: "Burs şeridi: UEG opportunities." },
  burs_esor: { label: 'RUNNER_REQUIRED', note: "Burs şeridi: ESOR training/exchange." },
  burs_efsd_easd: { label: 'RUNNER_REQUIRED', note: "Burs şeridi: EFSD/EASD current calls." },
  burs_eha_grants: { label: 'RUNNER_REQUIRED', note: "Burs şeridi: EHA research grants." },
  burs_ibro: { label: 'RUNNER_REQUIRED', note: "Burs şeridi: IBRO grants calendar." },
  burs_fens: { label: 'RUNNER_REQUIRED', note: "Burs şeridi: FENS grants/stipends." },
  burs_eular: { label: 'RUNNER_REQUIRED', note: "Burs şeridi: EULAR bursary/grant." },
  burs_iarc_who: { label: 'RUNNER_REQUIRED', note: "Burs şeridi: IARC postdoc; LMIC/UMIC." },
  burs_sigma_nursing: { label: 'RUNNER_REQUIRED', note: "Burs şeridi: Sigma nursing grants." },
  burs_uk_wellcome: { label: 'RUNNER_REQUIRED', note: "Burs şeridi: Wellcome ECA; host ülke değişiyor." },
  burs_tr_kyk: { label: 'RUNNER_REQUIRED', note: "Burs şeridi: KYK/GSB yıllık öğrenci burs-kredi." },
  burs_tr_tev: { label: 'RUNNER_REQUIRED', note: "Burs şeridi: TEV öğrenci bursu + tıp araştırma." },
  burs_tr_tubitak_2209: { label: 'RUNNER_REQUIRED', note: "Burs şeridi: 2209-A lisans araştırma projesi." },
  burs_tr_tubitak_2210: { label: 'RUNNER_REQUIRED', note: "Burs şeridi: 2210 yurt içi YL." },
  burs_tr_tubitak_2211: { label: 'RUNNER_REQUIRED', note: "Burs şeridi: 2211 yurt içi doktora." },
  burs_hu_stipendium: { label: 'RUNNER_REQUIRED', note: "Burs şeridi: Hungaricum; TR+tıp one-tier." },
  burs_tr_jean_monnet: { label: 'RUNNER_REQUIRED', note: "Burs şeridi: Jean Monnet; son sınıf+YL." },
  burs_fr_eiffel: { label: 'RUNNER_REQUIRED', note: "Burs şeridi: Eiffel; sağlık YL/doktora." },
  burs_kr_gks: { label: 'RUNNER_REQUIRED', note: "Burs şeridi: GKS; TR kontenjan; tıp listeye bağlı." },
  burs_ch_swiss_excellence: { label: 'RUNNER_REQUIRED', note: "Burs şeridi: Swiss Excellence; YL sonrası araştırma." },
  burs_us_cri: { label: 'RUNNER_REQUIRED', note: "Burs şeridi: CRI immuno-informatics postdoc; uyruk serbest." },
  burs_us_fraxa: { label: 'RUNNER_REQUIRED', note: "Burs şeridi: FRAXA fellowship; dünya lab." },
  burs_esicm_grants: { label: 'RUNNER_REQUIRED', note: "Burs şeridi: ESICM research grant; üyelik." },
  burs_espen_fellowships: { label: 'RUNNER_REQUIRED', note: "Burs şeridi: ESPEN klinik beslenme fellowship." },
  burs_febs_fellowships: { label: 'RUNNER_REQUIRED', note: "Burs şeridi: FEBS short-term; TBD üye." },
  burs_embo: { label: 'RUNNER_REQUIRED', note: "Burs şeridi: EMBO; TR EMBC üyesi." },
  burs_uk_mrc: { label: 'RUNNER_REQUIRED', note: "Burs şeridi: MRC fellowship; UK host; yalnız tıp." },
  burs_iti_scholarships: { label: 'RUNNER_REQUIRED', note: "Burs şeridi: ITI 1 yıllık implant bursu." },
  burs_esaic_grants: { label: 'RUNNER_REQUIRED', note: "Burs şeridi: ESAIC grant; TR Council ülkesi." },
  burs_us_morris: { label: 'RUNNER_REQUIRED', note: "Burs şeridi: Morris VSS; TR vet öğrencisi." },
  burs_us_pva: { label: 'RUNNER_REQUIRED', note: "Burs şeridi: PVA SCI fellowship; ABD/Kanada host." },
  burs_iubmb: { label: 'RUNNER_REQUIRED', note: "Burs şeridi: IUBMB Wood-Whelan; TBD üye." },
  burs_eso_doctors: { label: 'RUNNER_REQUIRED', note: "Burs şeridi: ESO Doctors Fellowship; 3-6 ay." },
  burs_fip_ecpg: { label: 'RUNNER_REQUIRED', note: "Burs şeridi: FIP ECPG/HAMIS; UMIC TR, üyelik şartı." },
  burs_icm_congress: { label: 'RUNNER_REQUIRED', note: "Burs şeridi: ICM ebelik kongre bursu; 2026 kapalı, üye dernek." },
  burs_isa_wca_travel: { label: 'RUNNER_REQUIRED', note: "Burs şeridi: WCA/ISA odyoloji seyahat hibesi; ISA sayfası manuel doğrulama." },
  burs_imperial_gozukara: { label: 'RUNNER_REQUIRED', note: "Burs şeridi: Imperial+Gözükara 8 hafta araştırma + £3000; 1 visiting TR kontenjanı listedeki fakülteler. 2026 penceresi kapandı." },
  egitim_ifm: { label: 'RUNNER_REQUIRED', note: "Eğitim şeridi: IFM eğitim hub; FMCP/AFMCP ayrı. TR practitioner kanıtı var. TUK uzmanlığı değil." },
  egitim_acam_chelation: { label: 'RUNNER_REQUIRED', note: "Eğitim şeridi: ileri kelasyon eğitimi; Türkiye yasağı yok, tanınmış klinik yetki gerekebilir" },
  egitim_cleveland_cfm: { label: 'RUNNER_REQUIRED', note: "Eğitim şeridi: named Functional Medicine preceptorship; TR excluded-country değil. Vize/CIME. Hasta bakımı/denklik değil." },
  egitim_stanford_integrative: { label: 'RUNNER_REQUIRED', note: "Eğitim şeridi: pediatrik integratif tıp eğitimi; program bazlı klinik uygunluk" },
  egitim_charite_im_summer: { label: 'RUNNER_REQUIRED', note: "Eğitim şeridi: yaz okulu; Türkiye dışlaması yok, Almanca/etkinlik koşulları var" },
  egitim_who_academy: { label: 'RUNNER_REQUIRED', note: "Eğitim şeridi: WHO Academy kurs kataloğu. OpenWHO acil sağlık ayrı kaynak." },
  egitim_hms_ce: { label: 'RUNNER_REQUIRED', note: "Eğitim şeridi: HMS CME kataloğu. HMX Fundamentals ayrı kaynak." },
  egitim_mayo_scpd: { label: 'RUNNER_REQUIRED', note: "Eğitim şeridi: açık CME kataloğu; etkinlik kuralları kurs bazlı" },
  egitim_lshtm_short: { label: 'RUNNER_REQUIRED', note: "Eğitim şeridi: uluslararası kısa kurs; önkoşullar kursa göre değişir" },
  egitim_pasteur: { label: 'RUNNER_REQUIRED', note: "Eğitim şeridi: MOOC dünya çapında açık; yüz yüze kabul program bazlı" },
  egitim_eso: { label: 'RUNNER_REQUIRED', note: "Eğitim şeridi: ESO eğitim kataloğu; tıp öğrencisi onkoloji kursu ayrı. Doctors Fellowship burs şeridinde." },
  egitim_eau: { label: 'RUNNER_REQUIRED', note: "Eğitim şeridi: eğitim/etkinlik kataloğu; burs/exchange üyelik şartlı ve burs şeridinde" },
  egitim_ean_learn: { label: 'RUNNER_REQUIRED', note: "Eğitim şeridi: öğrenme portalı; fellowship hattı burs şeridinde ayrı" },
  egitim_esaic_academy: { label: 'RUNNER_REQUIRED', note: "Eğitim şeridi: akademi kurs/masterclass; araştırma grant'ları burs şeridinde ayrı" },
  egitim_ers: { label: 'RUNNER_REQUIRED', note: "Eğitim şeridi: eğitim/bursiyer kayıtlı TR alıcı belgelenmiş; fellowship burs şeridinde" },
  egitim_eular: { label: 'RUNNER_REQUIRED', note: "Eğitim şeridi: Türk sağlık örgütü EULAR ağında; kurs/CME eğitim şeridi" },
  egitim_eha: { label: 'RUNNER_REQUIRED', note: "Eğitim şeridi: Türk Hematoloji Derneği bağlantısı; grant hattı burs şeridinde" },
  egitim_fens: { label: 'RUNNER_REQUIRED', note: "Eğitim şeridi: eğitim/kurs; exchange fellowship burs şeridinde ayrı" },
  egitim_febs_courses: { label: 'RUNNER_REQUIRED', note: "Eğitim şeridi: ileri kurslar; short-term fellowship burs şeridinde ayrı" },
  egitim_bif_travel: { label: 'RUNNER_REQUIRED', note: "Eğitim şeridi: pratik kurs ve araştırma ziyareti seyahat hibesi; dünya çapında MD/PhD" },
  egitim_eons_eso_nurses: { label: 'RUNNER_REQUIRED', note: "Eğitim şeridi: yapılandırılmış kanser hemşireliği klinik yerleştirmesi; Türkiye yasağı yok" },
  egitim_esso: { label: 'RUNNER_REQUIRED', note: "Eğitim şeridi: kurs/webinar eğitim şeridi; educational grant burs şeridinde ayrı" },
  egitim_isglobal: { label: 'RUNNER_REQUIRED', note: "Eğitim şeridi: uluslararası eğitim portföyü; kabul program bazlı" },
  egitim_wcmq_cpd: { label: 'RUNNER_REQUIRED', note: "Eğitim şeridi: grand round ve araştırma yöntemleri CPD; bazı etkinlik Katar odaklı" },
  egitim_monash_pd: { label: 'RUNNER_REQUIRED', note: "Eğitim şeridi: uluslararası kısa kurs/mikro-kredi; tanıma program bazlı" },
  egitim_wfot: { label: 'RUNNER_REQUIRED', note: "Eğitim şeridi: WFOT; Türk Ergoterapi Derneği tam üye, onaylı programlar." },
  egitim_world_physio: { label: 'RUNNER_REQUIRED', note: "Eğitim şeridi: World Physiotherapy kongre/eğitim; 2027 konuşmacı bursu LMIC-only alınmadı." },
  egitim_espen_training: { label: 'RUNNER_REQUIRED', note: "Eğitim şeridi: ESPEN klinik beslenme eğitim merkezleri; KEPAN/TR merkezler. Fellowship burs şeridinde." },
  egitim_ifm_fmcp: { label: 'RUNNER_REQUIRED', note: "Eğitim şeridi: FMCP/FMCP-M; uluslararası eşdeğer lisans. TR practitioner kanıtı. Mevcut meslek lisansını genişletmez." },
  egitim_ifm_afmcp: { label: 'RUNNER_REQUIRED', note: "Eğitim şeridi: ACCME 11 hafta online AFMCP; TR coursework kanıtı. FMCP otomatik değil. Klinik ruhsat değil." },
  egitim_cleveland_observership: { label: 'RUNNER_REQUIRED', note: "Eğitim şeridi: named 1 ay CIME observership; Functional Medicine listede. Vize/CIME. Hasta bakımı yok." },
  egitim_uws_cnfm: { label: 'RUNNER_REQUIRED', note: "Eğitim şeridi: NWCCU üniversite graduate certificate, %100 online. TR denklik/licensure değil." },
  egitim_kresser_adapt: { label: 'RUNNER_REQUIRED', note: "Eğitim şeridi: 12 ay sanal ADAPT; international açık. Bağımsız board/NCCA doğrulanmadı. İzlenmeli." },
  egitim_fmca: { label: 'RUNNER_REQUIRED', note: "Eğitim şeridi: NBHWC/UKIHCA health-coach; TR mezun kanıtı. Hekimlik/klinik yetki değil." },
  egitim_egfm: { label: 'RUNNER_REQUIRED', note: "Eğitim şeridi: EGFM Almanca; Berlin Tabip Odası CME. TR meslek belgesi otomatik kabul değil." },
  egitim_nih_ippcr: { label: 'RUNNER_REQUIRED', note: "Eğitim şeridi: NIH IPPCR ücretsiz online; tıp/diş öğrencileri hedefte. 2026–27 açık. CME yok." },
  egitim_hms_hmx: { label: 'RUNNER_REQUIRED', note: "Eğitim şeridi: HMS HMX Fundamentals; tıp ve sağlık öğrencileri. Certificate of Completion. CME kataloğundan ayrı." },
  egitim_eso_medstudents: { label: 'RUNNER_REQUIRED', note: "Eğitim şeridi: 1 hafta yüz yüze öğrenci onkoloji kursu; 40 kişilik seçim. 2026 kapalı. Vize." },
  egitim_esmo_students: { label: 'RUNNER_REQUIRED', note: "Eğitim şeridi: ESMO tıp öğrencisi medikal onkoloji kursu. 4.–5. sınıf. Vize. Fellowship burs şeridinde ayrı." },
  egitim_ucl_moorfields_oss: { label: 'RUNNER_REQUIRED', note: "Eğitim şeridi: UCL/Moorfields 5 gün oftalmoloji yaz okulu; uluslararası late-stage öğrenciler. Vize." },
  egitim_erasmus_summer: { label: 'RUNNER_REQUIRED', note: "Eğitim şeridi: Erasmus MC 3 hafta Rotterdam; Master/PhD düzey. Her tıp öğrencisi otomatik uygun değil." },
  egitim_openwho: { label: 'RUNNER_REQUIRED', note: "Eğitim şeridi: OpenWHO acil sağlık; ücretsiz global. 2025 sonrası sertifika yok. WHO Academy ayrı." },
};

export function coverageLabel(
  sourceId: string,
  row: { coverage_status?: string | null; source_health?: string | null; last_success_at?: string | null } | null
): { label: CoverageLabel; note: string } {
  const o = COVERAGE_OVERRIDES[sourceId];
  if (o) return o;
  if (!row || !row.last_success_at) {
    return { label: row ? 'FAILED_INTERNAL' : 'NOT_RUN', note: row ? 'Başarılı koşu yok.' : 'Henüz koşu yok.' };
  }
  if (row.source_health === 'DEGRADED' || row.coverage_status === 'RUN_FAILED') {
    return { label: 'FAILED_INTERNAL', note: 'Son koşu başarısız.' };
  }
  if (row.coverage_status === 'NO_ELIGIBLE_ITEMS') {
    return { label: 'PIPELINE_OK_EMPTY', note: 'Çalışıyor; güncel uygun içerik yok.' };
  }
  return { label: 'PIPELINE_OK', note: '' };
}
