-- Longevity / functional medicine / dietetics / supplements batch (2026-09-25).
-- Bible §24: journals + NIH/FDA = verification-grade; ScienceDaily = discovery only.
-- Journals ingest via official PubMed E-utilities [ta] (same pattern as 0015/0016), not WAF-blocked publisher sites.
-- RSS hubs/news were curl-verified live this batch (real <rss>/<item> bodies).
-- Not in this migration (see operator report): IFM 403, ODS 403, Mayo/Examine/HelpGuide/HSIS out of scope,
-- Medical Xpress topic RSS 404 (homepage already live), ScienceDaily Nutrition already on Hekimler,
-- NIH News Releases already live, Nature Nutritional Supplements hub is HTML not RSS,
-- FDA dietary-supplements landing page has no RSS (MedWatch covers safety alerts).
INSERT OR IGNORE INTO source_feeds (id, label, route, channel_id, transport, endpoint_url, poll_minutes, enabled, external_ref, rules_json)
VALUES
('research-pubmed-nat-aging', 'Nature Aging (via PubMed)', 'kaduse-research', 'kaduse-medikal', 'PUBMED_EUTILS', 'https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi', 43200, 1, 'pubmed-journal-nat-aging', '{"term":"\"Nat Aging\"[ta]","retmax":15}'),
('research-pubmed-front-aging', 'Frontiers in Aging (via PubMed)', 'kaduse-research', 'kaduse-medikal', 'PUBMED_EUTILS', 'https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi', 43200, 1, 'pubmed-journal-front-aging', '{"term":"\"Front Aging\"[ta]","retmax":15}'),
('research-pubmed-jicm', 'Journal of Integrative and Complementary Medicine (via PubMed)', 'kaduse-research', 'kaduse-medikal', 'PUBMED_EUTILS', 'https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi', 43200, 1, 'pubmed-journal-jicm', '{"term":"\"J Integr Complement Med\"[ta]","retmax":15}'),
('research-pubmed-bmc-cmt', 'BMC Complementary Medicine and Therapies (via PubMed)', 'kaduse-research', 'kaduse-medikal', 'PUBMED_EUTILS', 'https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi', 43200, 1, 'pubmed-journal-bmc-cmt', '{"term":"\"BMC Complement Med Ther\"[ta]","retmax":15}'),
('research-pubmed-nutrients', 'Nutrients (via PubMed)', 'kaduse-research', 'kaduse-medikal', 'PUBMED_EUTILS', 'https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi', 43200, 1, 'pubmed-journal-nutrients', '{"term":"\"Nutrients\"[ta]","retmax":15}'),
('research-pubmed-bmj-nph', 'BMJ Nutrition, Prevention & Health (via PubMed)', 'kaduse-research', 'kaduse-medikal', 'PUBMED_EUTILS', 'https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi', 43200, 1, 'pubmed-journal-bmj-nph', '{"term":"\"BMJ Nutr Prev Health\"[ta]","retmax":15}'),
('research-pubmed-j-diet-suppl', 'Journal of Dietary Supplements (via PubMed)', 'kaduse-research', 'kaduse-medikal', 'PUBMED_EUTILS', 'https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi', 43200, 1, 'pubmed-journal-j-diet-suppl', '{"term":"\"J Diet Suppl\"[ta]","retmax":15}'),
('research-pubmed-front-nutr', 'Frontiers in Nutrition (via PubMed)', 'kaduse-research', 'kaduse-medikal', 'PUBMED_EUTILS', 'https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi', 43200, 1, 'pubmed-journal-front-nutr', '{"term":"\"Front Nutr\"[ta]","retmax":15}'),
('research-pubmed-aging-longevity', 'PubMed — aging / longevity discovery', 'kaduse-research', 'kaduse-medikal', 'PUBMED_EUTILS', 'https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi', 43200, 1, 'pubmed-query-aging-longevity', '{"term":"(longevity[ti] OR geroscience[ti] OR \"healthy aging\"[ti] OR \"biological age\"[ti]) AND (2025:2026[dp])","retmax":15}'),
('research-pubmed-integrative', 'PubMed — integrative / complementary discovery', 'kaduse-research', 'kaduse-medikal', 'PUBMED_EUTILS', 'https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi', 43200, 1, 'pubmed-query-integrative', '{"term":"(\"functional medicine\"[ti] OR \"integrative medicine\"[ti] OR \"complementary medicine\"[ti]) AND (2025:2026[dp])","retmax":15}'),
('research-pubmed-supplements', 'PubMed — dietary supplement trials / reviews', 'kaduse-research', 'kaduse-medikal', 'PUBMED_EUTILS', 'https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi', 43200, 1, 'pubmed-query-supplements', '{"term":"(\"dietary supplement\"[ti] OR nutraceutical[ti] OR \"food supplement\"[ti]) AND (clinical trial[pt] OR systematic review[pt] OR meta-analysis[pt]) AND (2025:2026[dp])","retmax":15}'),
('research-nature-ageing-hub', 'Nature — Ageing subject hub', 'kaduse-research', 'kaduse-medikal', 'WEB_ONLY', 'https://www.nature.com/subjects/ageing.rss', 1440, 1, 'nature-ageing-subject', '{"mode":"registered","bibleRole":"PRIMARY"}'),
('research-nature-nutrition-hub', 'Nature — Nutrition subject hub', 'kaduse-research', 'kaduse-medikal', 'WEB_ONLY', 'https://www.nature.com/subjects/nutrition.rss', 1440, 1, 'nature-nutrition-subject', '{"mode":"registered","bibleRole":"PRIMARY"}'),
('research-sciencedaily-healthy-aging', 'ScienceDaily — Healthy Aging', 'kaduse-research', 'kaduse-medikal', 'WEB_ONLY', 'https://www.sciencedaily.com/rss/health_medicine/healthy_aging.xml', 1440, 1, 'sciencedaily-healthy-aging', '{"mode":"registered","bibleRole":"DISCOVERY_ONLY"}'),
('research-sciencedaily-alternative-medicine', 'ScienceDaily — Alternative Medicine', 'kaduse-research', 'kaduse-medikal', 'WEB_ONLY', 'https://www.sciencedaily.com/rss/health_medicine/alternative_medicine.xml', 1440, 1, 'sciencedaily-alternative-medicine', '{"mode":"registered","bibleRole":"DISCOVERY_ONLY"}'),
('research-sciencedaily-dietary-supplements', 'ScienceDaily — Dietary Supplements', 'kaduse-research', 'kaduse-medikal', 'WEB_ONLY', 'https://www.sciencedaily.com/rss/health_medicine/dietary_supplements.xml', 1440, 1, 'sciencedaily-dietary-supplements', '{"mode":"registered","bibleRole":"DISCOVERY_ONLY"}'),
('research-asn-news', 'American Society for Nutrition — News', 'kaduse-research', 'kaduse-medikal', 'WEB_ONLY', 'https://nutrition.org/feed/', 1440, 1, 'asn-nutrition-news', '{"mode":"registered","bibleRole":"PRIMARY"}'),
('research-nccih-news', 'NCCIH News (NIH)', 'kaduse-research', 'kaduse-medikal', 'WEB_ONLY', 'https://www.ncbi.nlm.nih.gov/feed/rss.cgi?ChanKey=NCCIHNews', 1440, 1, 'nccih-news', '{"mode":"registered","bibleRole":"PRIMARY"}'),
('news-fda-medwatch-supplements', 'FDA MedWatch — dietary supplement safety', 'kaduse-news', 'kaduse-medikal', 'WEB_ONLY', 'https://www.fda.gov/about-fda/contact-fda/stay-informed/rss-feeds/medwatch/rss.xml', 360, 1, 'fda-medwatch-supplements', '{"includeKeywords":["supplement","vitamin","mineral","botanical","dietary","nutraceutical","herb"],"bibleRole":"PRIMARY"}');
