-- Second longevity / integrative / dietetics / supplements batch (2026-09-25).
-- Journals: official PubMed E-utilities [ta] (Oxford/Cambridge/ScienceDirect RSS is 403/HTML or would duplicate PubMed).
-- EFSA news+publications RSS live-checked. FDA Tainted Supplements RSS live-checked (legacy AboutFDA path).
-- Already in D1 from 0015: AJCN, Nutrition Reviews, Journal of Nutrition, Current Developments in Nutrition.
-- Not in this migration: Academic Consortium (403), NutraIngredients / USA / Nutrition Insight / Nutraceuticals World (RSS 404/403).
INSERT OR IGNORE INTO source_feeds (id, label, route, channel_id, transport, endpoint_url, poll_minutes, enabled, external_ref, rules_json)
VALUES
('research-pubmed-nat-metab', 'Nature Metabolism (via PubMed)', 'kaduse-research', 'kaduse-medikal', 'PUBMED_EUTILS', 'https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi', 43200, 1, 'pubmed-journal-nat-metab', '{"term":"\"Nat Metab\"[ta]","retmax":15}'),
('research-pubmed-jgosa', 'Journals of Gerontology Series A (via PubMed)', 'kaduse-research', 'kaduse-medikal', 'PUBMED_EUTILS', 'https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi', 43200, 1, 'pubmed-journal-jgosa', '{"term":"\"J Gerontol A Biol Sci Med Sci\"[ta]","retmax":15}'),
('research-pubmed-age-ageing', 'Age and Ageing (via PubMed)', 'kaduse-research', 'kaduse-medikal', 'PUBMED_EUTILS', 'https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi', 43200, 1, 'pubmed-journal-age-ageing', '{"term":"\"Age Ageing\"[ta]","retmax":15}'),
('research-pubmed-gerontologist', 'The Gerontologist (via PubMed)', 'kaduse-research', 'kaduse-medikal', 'PUBMED_EUTILS', 'https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi', 43200, 1, 'pubmed-journal-gerontologist', '{"term":"\"Gerontologist\"[ta]","retmax":15}'),
('research-pubmed-exp-gerontol', 'Experimental Gerontology (via PubMed)', 'kaduse-research', 'kaduse-medikal', 'PUBMED_EUTILS', 'https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi', 43200, 1, 'pubmed-journal-exp-gerontol', '{"term":"\"Exp Gerontol\"[ta]","retmax":15}'),
('research-pubmed-mech-ageing', 'Mechanisms of Ageing and Development (via PubMed)', 'kaduse-research', 'kaduse-medikal', 'PUBMED_EUTILS', 'https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi', 43200, 1, 'pubmed-journal-mech-ageing', '{"term":"\"Mech Ageing Dev\"[ta]","retmax":15}'),
('research-pubmed-ctm', 'Complementary Therapies in Medicine (via PubMed)', 'kaduse-research', 'kaduse-medikal', 'PUBMED_EUTILS', 'https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi', 43200, 1, 'pubmed-journal-ctm', '{"term":"\"Complement Ther Med\"[ta]","retmax":15}'),
('research-pubmed-imr', 'Integrative Medicine Research (via PubMed)', 'kaduse-research', 'kaduse-medikal', 'PUBMED_EUTILS', 'https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi', 43200, 1, 'pubmed-journal-imr', '{"term":"\"Integr Med Res\"[ta]","retmax":15}'),
('research-pubmed-explore', 'EXPLORE: The Journal of Science & Healing (via PubMed)', 'kaduse-research', 'kaduse-medikal', 'PUBMED_EUTILS', 'https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi', 43200, 1, 'pubmed-journal-explore', '{"term":"\"Explore (NY)\"[ta]","retmax":15}'),
('research-pubmed-br-j-nutr', 'British Journal of Nutrition (via PubMed)', 'kaduse-research', 'kaduse-medikal', 'PUBMED_EUTILS', 'https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi', 43200, 1, 'pubmed-journal-br-j-nutr', '{"term":"\"Br J Nutr\"[ta]","retmax":15}'),
('research-pubmed-ph-nutr', 'Public Health Nutrition (via PubMed)', 'kaduse-research', 'kaduse-medikal', 'PUBMED_EUTILS', 'https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi', 43200, 1, 'pubmed-journal-ph-nutr', '{"term":"\"Public Health Nutr\"[ta]","retmax":15}'),
('research-pubmed-clin-nutr', 'Clinical Nutrition (via PubMed)', 'kaduse-research', 'kaduse-medikal', 'PUBMED_EUTILS', 'https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi', 43200, 1, 'pubmed-journal-clin-nutr', '{"term":"\"Clin Nutr\"[ta]","retmax":15}'),
('news-efsa-news', 'EFSA News', 'kaduse-news', 'kaduse-medikal', 'WEB_ONLY', 'https://www.efsa.europa.eu/en/news/rss', 360, 1, 'efsa-news', '{"includeKeywords":["supplement","vitamin","mineral","nutrient","novel food","health claim","botanic","nutraceutical","food additive","herbal","amino acid","isoflavone","food supplement"],"bibleRole":"PRIMARY"}'),
('news-efsa-publications', 'EFSA Publications', 'kaduse-news', 'kaduse-medikal', 'WEB_ONLY', 'https://www.efsa.europa.eu/en/publications/rss', 1440, 1, 'efsa-publications', '{"includeKeywords":["supplement","vitamin","mineral","nutrient","novel food","health claim","botanic","nutraceutical","food additive","herbal","amino acid","isoflavone","food supplement"],"bibleRole":"PRIMARY"}'),
('news-fda-tainted-supplements', 'FDA Tainted Supplements', 'kaduse-news', 'kaduse-medikal', 'WEB_ONLY', 'https://www.fda.gov/AboutFDA/ContactFDA/StayInformed/RSSFeeds/TDS/rss.xml', 360, 1, 'fda-tainted-supplements', '{"bibleRole":"PRIMARY"}');
