-- 0030 PubMed carrier reconciliation (production state drift; NOT a lifecycle state change).
-- Canonical source id: research-pubmed-eutilities; lifecycle source id: pubmed-eutilities.
-- Reason: production D1 drifted from the canonical catalog with no migration/history evidence (checked 2026-10-02, read-only).
-- Old (production D1): enabled=0, poll_minutes=1440.  Target (config/feeds.json): enabled=1, poll_minutes=360.
-- All other managed columns were verified identical, so the upsert below changes exactly these two columns.
-- Time-sensitive path stays OFF (temporal-paths.json time_sensitive.enabled=false): ingestPubmed is gated before any network access,
-- so enabling this row only makes it the EVERGREEN write carrier. No source_items, temporal path, trigger or backfill is touched.
-- Generated through scripts/source-lifecycle/kaduse-change.mjs diffFeeds + forwardMigrationSql (existing lifecycle generator).
-- Generated by scripts/source-lifecycle.mjs (reconcile-carrier-drift research-pubmed-eutilities (lifecycle id pubmed-eutilities), request pubmed-carrier-drift-2026-10-02) from the config/feeds.json diff.
-- Forward-only; catalog-owned columns only. Remote apply requires explicit authorization.

INSERT INTO source_feeds (id, label, route, channel_id, transport, endpoint_url, poll_minutes, enabled, external_ref, rules_json)
VALUES ('research-pubmed-eutilities', 'NLM / NCBI (PubMed)', 'kaduse-research', 'kaduse-medikal', 'REST_BATCH', 'https://eutils.ncbi.nlm.nih.gov/entrez/eutils/', 360, 1, 'pubmed-eutilities', '{"term":"(auscultation OR stethoscope OR (\"artificial intelligence\" AND medicine))","retmax":15}')
ON CONFLICT(id) DO UPDATE SET label = excluded.label, route = excluded.route, channel_id = excluded.channel_id, transport = excluded.transport, endpoint_url = excluded.endpoint_url, poll_minutes = excluded.poll_minutes, enabled = excluded.enabled, external_ref = excluded.external_ref, rules_json = excluded.rules_json;
