-- Generated by scripts/source-lifecycle.mjs (add www-medikalnews-whole, request slr_aa78afb93f48d40b) from the config/feeds.json diff.
-- Forward-only; catalog-owned columns only. Remote apply requires explicit authorization.

INSERT INTO source_feeds (id, label, route, channel_id, transport, endpoint_url, poll_minutes, enabled, external_ref, rules_json)
VALUES ('news-www-medikalnews-whole', 'Medikal News', 'kaduse-news', 'kaduse-medikal', 'WEB_ONLY', 'https://www.medikalnews.com/sitemap.rss', 60, 1, 'www-medikalnews-whole', '{"mode":"registered","needsFetcher":true,"inclusionPolicy":null,"exclusionPolicy":null}')
ON CONFLICT(id) DO UPDATE SET label = excluded.label, route = excluded.route, channel_id = excluded.channel_id, transport = excluded.transport, endpoint_url = excluded.endpoint_url, poll_minutes = excluded.poll_minutes, enabled = excluded.enabled, external_ref = excluded.external_ref, rules_json = excluded.rules_json;
