// Generated by `node scripts/relevance-loop.mjs bundle` from config/relevance-ledger.json. Do not edit by hand.
export type RelevanceAdjustment = { adjustment_id: string; channel_id: string; dimension: 'source' | 'content_family' | 'topic'; key: string; direction: 'lower' | 'raise'; delta: number };
export const RELEVANCE_ADJUSTMENTS: readonly RelevanceAdjustment[] = [];
